/**
 * Nuxt v4 auto-import resolution for the TypeScript scope-resolver.
 *
 * Nuxt and Nitro both make symbols available project-wide without explicit
 * import statements. Two sources cover the common cases:
 *
 *   1. `.nuxt/imports.d.ts` - client/shared composables generated by Nuxt at
 *      build time. Only entries whose source is a project-local relative path
 *      (i.e. NOT a package in node_modules or a Nuxt runtime alias) are
 *      indexed. These are project utils and composables the developer wrote.
 *
 *   2. `server/utils/**` - Nitro auto-imports all exports from this directory
 *      tree into every `server/api/`, `server/routes/`, and
 *      `server/middleware/` file. These are not included in `imports.d.ts`
 *      because they are server-only.
 *
 * The two sources are kept in separate maps because their visibility scopes
 * differ: app/client files do not see `server/utils`, while Nitro server
 * handlers prefer same-named server utilities over client composables.
 *
 * Detection: if `.nuxt/imports.d.ts` is absent the repo is not a Nuxt project
 * and this module returns null immediately, adding zero overhead to non-Nuxt
 * analysis runs. The `server/utils` scan is only attempted when the Nuxt
 * detection succeeds, so it also costs nothing for non-Nuxt repos.
 *
 * Limitations:
 *   - Auto-import edges are still heuristic rather than type-checked. The
 *     emitter tags them with confidence 0.75.
 *   - Re-exports with non-matching aliases (e.g. `flatUnwrap as unwrapSlot`
 *     where `flatUnwrap` is the graph node name) try both the original export
 *     name and the local alias when looking up the graph node.
 *   - Only direct exports are indexed; barrel re-exports that chain through
 *     multiple files are not followed.
 */
export type NuxtAutoImportScope = 'client' | 'server';
/** A single auto-imported symbol and where it lives in the repo. */
export interface NuxtAutoImportEntry {
    /** The name used at call sites (the alias when `export { X as Y }` form). */
    readonly localName: string;
    /** The original export name in the source file (before `as`). */
    readonly exportName: string;
    /** Repo-relative POSIX path to the source file (with extension). */
    readonly sourceFile: string;
    /** Which Nuxt/Nitro visibility scope supplied this entry. */
    readonly scope: NuxtAutoImportScope;
}
/**
 * Aggregated auto-import maps for one Nuxt workspace, keyed by the local
 * name used in calling code. Client/shared entries come from
 * `.nuxt/imports.d.ts`; server entries come from `server/utils`.
 */
export interface NuxtAutoImportConfig {
    readonly clientByLocalName: ReadonlyMap<string, NuxtAutoImportEntry>;
    readonly serverByLocalName: ReadonlyMap<string, NuxtAutoImportEntry>;
}
/**
 * Load the Nuxt auto-import map for `repoRoot`.
 *
 * Returns null when:
 *   - `.nuxt/imports.d.ts` does not exist (non-Nuxt project or pre-build), or
 *   - the file exists but yields zero project-local entries and `server/utils`
 *     is absent or empty.
 *
 * The `server/utils` scan is only attempted when `.nuxt/imports.d.ts` was
 * successfully read, confirming this is an initialized Nuxt project. This
 * avoids partial results from repos that have a `server/utils` directory but
 * are not Nuxt projects.
 */
export declare function loadNuxtAutoImports(repoRoot: string): Promise<NuxtAutoImportConfig | null>;
export declare function hasNuxtAutoImports(config: NuxtAutoImportConfig): boolean;
export declare function getNuxtAutoImportEntry(config: NuxtAutoImportConfig, localName: string, callerFile: string): NuxtAutoImportEntry | undefined;
export declare function isNitroServerRuntimeFile(filePath: string): boolean;
