spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka.temporal-demo.svc.cluster.local:9092}
app.kafka.topic=${KAFKA_TOPIC:payment-worker.events}
spring.kafka.consumer.auto-offset-reset=earliest
