spring.application.name=merchant-api
server.port=8106
spring.data.mongodb.uri=${MONGODB_URI:mongodb://127.0.0.1:27017/merchant_api}
spring.data.mongodb.auto-index-creation=true
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka.temporal-demo.svc.cluster.local:9092}
spring.kafka.consumer.auto-offset-reset=earliest
app.kafka.topic=${KAFKA_TOPIC:merchant-api.events}
app.temporal.task-queue=${TEMPORAL_TASK_QUEUE:merchant-api}
