module(name = "accounting_api", version = "1.0.0")

bazel_dep(name = "rules_java", version = "9.2.0")
bazel_dep(name = "rules_jvm_external", version = "6.7")
maven = use_extension("@rules_jvm_external//:extensions.bzl", "maven")
maven.install(
    artifacts = [
        "io.temporal:temporal-sdk:1.26.2",
        "org.springframework.boot:spring-boot-starter:3.3.5",
        "org.springframework.boot:spring-boot-starter-data-mongodb:3.3.5",
        "org.springframework.boot:spring-boot-starter-web:3.3.5",
        "org.springframework.kafka:spring-kafka:3.2.5",
    ],
    repositories = ["https://repo1.maven.org/maven2"],
)
use_repo(maven, "maven")
