spring.application.name=workflow-api
server.port=8080
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka.temporal-demo.svc.cluster.local:9092}
app.kafka.topic=${KAFKA_TOPIC:workflow-api.events}
spring.kafka.consumer.auto-offset-reset=earliest
